FROM atomi/nodejs:latest

RUN npm install -g less@beta \ 
									 sass \
									 which \
									 bower \
									 grunt-cli \
									 gulp \
									 yo \
									 generator-angular \
									 matchdep \
									 wiki \
									 brunch \
									 coffee-script && \
		npm cache clear
